const chipLabels = [
  "Restaurants, Cafe's & Bar",
  "Kids Play Area",
  "Auditorium",
  "Ballroom",
  "Dance Studio",
  "Conference Center",
  "Museum",
  "Gallery",
  "Indoor With Outdoor Space",
  "Hotel",
  "Schools",
  "Meeting room",
  "Exhibition Center",
  "Meeting Center",
  "Photo Studio",
  "Beach",
  "Garden/Lawn",
  "Music Studio",
  "Heritage Site",
  "Stables",
  "Convention Centers",
  "Arcade",
  "Parks",
  "Sports Center",
  "Desert",
  "Island",
  "Golf Course",
  "University",
  "Pop up Space",
  "Stadium",
  "Boats & Yachts",
  "Concert Halls",
  "Race Course",
  "Theme Park",
  "Rooftop Venues",
  "Theatre",
  "Unique Spaces",
  "Religious Venue",
  "Coworking Space",
];

export default chipLabels;
